### ISSUE TITLE
pypugjs.ext.jinja is broken in 

### ISSUE THREAD

**Issue by MarSoft** [kakulukia/pypugjs#73]
* pypugjs version: 5.9.10
* Flask version: Flask==2.0.3, Jinja2==3.1.1
* Python version: 3.10.2
* Operating System: Linux

### Description

Importing  `pypugjs.ext.jinja` fails because of missing `jinja2.Markup`.

### What I Did

```
Traceback (most recent call last):
  File "/tmp/env/lib/python3.10/site-packages/flask/cli.py", line 260, in locate_app
    __import__(module_name)
  File "/tmp/app.py", line 16, in <module>
    from pypugjs.ext.jinja import PyPugJSExtension
  File "/tmp/env/lib/python3.10/site-packages/pypugjs/ext/jinja.py", line 3, in <module>
    from jinja2 import Markup
ImportError: cannot import name 'Markup' from 'jinja2' (/home/mars/work/asmpatch/armconverter-web/env/lib/python3.10/site-packages/jinja2/__init__.py)
```

According to [Jinja2 changelog](https://github.com/pallets/jinja/blob/main/CHANGES.rst#version-310), `Markup` should now be imported from `MarkupSafe`.

**Comment by kakulukia** [comment]
This looks like any easy fix. Wait a moment.

**Comment by kakulukia** [comment]
Ehm ..... you might have to use Python 3.9 - i also saw something broken with 3.10 - not sure if it was inside pypugjs code tho or other dependencies. I also updated them to the latest versions - so please report back after testing.

**Comment by kakulukia** [comment]
I had a further look .. its "just" the testing framework nose that is fairly out of date and will not work with python 3.10 - pupugjs might work just fine tho.

**Comment by kakulukia** [comment]
@MarSoft can we close this ticket?

**Comment by MarSoft** [comment]
Yep. Alas, I don't currently have time to test, but I think it should work.
